name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up CMake
      run: sudo apt-get install -y cmake
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
    - name: Run the executable
      run: |
        cd build
        ./FIPS
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
